url: http://panda-curry.github.io
baseurl: ""

# Site Settings
title: ʕっ•ᴥ•ʔっ With Me
description: "beary nice!"
keywords: "Tarot, Numerology, Astrology, Bears"
collections:
 blog:
    name: blog
    output: true
 notes:
    name: Notes
    documentation: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
    output: true
markdown: kramdown

highlighter: rouge
exclude: ["Rakefile", "LICENSE", "readme.md"]
